- name: Configure App
  hosts: app
  become: true  
  vars:
    db_host: 192.168.10.29
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: restart puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser
      notify: restart puma

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: restart puma
    become: true
    systemd: 
      daemon_reload: yes
      name: puma 
      state: restarted
